sudo: required
os: trusty
language: php
php:
  - 7.2

before_script:
  - git clone git@github.com:wayneashleyberry/laravel-test.git
  - cd laravel-test
  - cp .env.travis .env
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - php artisan migrate

before_install:
  - mysql -e 'CREATE DATABASE mpr;'

script:
  - vendor/bin/phpunit

services:
  - mysql
